/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import model.TableroCoordenadas;

/**
 *
 * @author Alessandro
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        /*this.addMouseListener(new MouseAdapter ()
                {
                    @Override
                    public void mousePressed (MouseEvent e)
                    {
                    Point p = e.getPoint();
                    clickFicha(p);
                    }//fin metodo
                });*/
    }

    private TableroCoordenadas tablero;
    
    public JLabel getImgFichaRoja() {
        return imgFichaRoja;
    }

    public JLabel getImgTablero() {
        return imgTablero;
    }

    public void setTableroCoordenadas(TableroCoordenadas tablero){
        
        this.tablero=tablero;
        
    }//fin setTableroCoordenadas
    
    /* public void clickFicha (Point p)
    {
       imgFichaRoja.setLocation(p);
       System.out.println("Coordenadas :" + p.x + " , "+ p.y +".");
    }*/
    
    public void moverFicha (int colorId, int x , int y)
    {
      JLabel lbl = labelJugador(colorId); 
      if(lbl!= null)
      {
          lbl.setLocation(x, y);
          lbl.repaint();
          this.repaint();
      }//fin if
    }
    
    public JLabel labelJugador (int colorId)
    {
        
        if(colorId==0)
        {
            return imgFichaRoja;
        }
        if (colorId==1)
        {
            return imgFichaAmarilla;
        }//fin if2
        if(colorId==2)
        {
            return imgFichaAzul;
        }//fin if3
        return imgFichaVerde;
        

     

    }//fin
    
    public void repintar (int x, int y)
    {
        imgFichaRoja.setLocation(x, y);
        imgFichaRoja.repaint();
    }//fin repintar
            
            
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFichaVerde = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaAmarilla = new javax.swing.JLabel();
        imgFichaRoja = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(null);

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde);
        imgFichaVerde.setBounds(70, 390, 21, 31);

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul);
        imgFichaAzul.setBounds(400, 60, 21, 31);

        imgFichaAmarilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAmarilla);
        imgFichaAmarilla.setBounds(400, 390, 21, 32);

        imgFichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaRoja.png"))); // NOI18N
        add(imgFichaRoja);
        imgFichaRoja.setBounds(80, 70, 20, 30);

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tablerografico.png"))); // NOI18N
        add(imgTablero);
        imgTablero.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAmarilla;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaRoja;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
