package view;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Coordenadas;
import model.TableroCoordenadas;
/**
 *
 * @author Alessandro
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    TableroCoordenadas tc = new TableroCoordenadas();
    private PanelTablero pt;
    public PanelControl() {
        initComponents();
    }

    // --- SETTERS prácticos para mostrar info ---
    public void setNumeroDado(int valor) {
        lblNumeroDeDado.setText("Numero dado: " + valor);
    }

    public void setTextoTurno(String texto) {
        lblTurnoDeFicha.setText("Ficha turno: " + texto);
    }
    
    public void setPanelTablero(PanelTablero tableroVisible)
    {
        this.pt= tableroVisible;
    }//fin set

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public JLabel getLblNumeroDeDado() {
        return lblNumeroDeDado;
    }

    public JLabel getLblTurnoDeFicha() {
        return lblTurnoDeFicha;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblNumeroDeDado = new javax.swing.JLabel();
        lblTurnoDeFicha = new javax.swing.JLabel();

        btnDado.setText("Dado");
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reinicio");

        btnMenu.setText("Menu");

        lblNumeroDeDado.setText("Numero de dado");

        lblTurnoDeFicha.setText("Turno de ficha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnMenu)
                        .addGap(28, 28, 28)
                        .addComponent(btnReinicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnDado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblNumeroDeDado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTurnoDeFicha)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTurnoDeFicha)
                .addGap(42, 42, 42)
                .addComponent(lblNumeroDeDado)
                .addGap(1, 1, 1)
                .addComponent(btnDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnReinicio))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:
        Coordenadas [] recorrido = tc.getRecorrido();
        for(int i= 0; i<recorrido.length; i++)
        {
           int x = recorrido[i].getX();
           int y = recorrido[i].getY();
           pt.repintar(x, y);
           String eleccion= JOptionPane.showInputDialog("desea continuar?\nDigite ´no´ para parar");
           if(eleccion.equalsIgnoreCase("no"))
           {
               break;
           }
           else
           {
               
               
           }
        }//fin for
    }//GEN-LAST:event_btnDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblNumeroDeDado;
    private javax.swing.JLabel lblTurnoDeFicha;
    // End of variables declaration//GEN-END:variables
}
