package view;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Coordenadas;
import model.TableroCoordenadas;
/**
 *
 * @author Alessandro
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    TableroCoordenadas tc = new TableroCoordenadas();
    private PanelTablero pt;
    public PanelControl() {
        initComponents();
    }

    // --- SETTERS prácticos para mostrar info ---
    public void setNumeroDado(int valor) {
        txtNumeroDeDado.setText("Numero dado: " + valor);
    }

    public void setFichaTurno(String texto) {
        txtTurnoDeFicha.setText("Ficha turno: " + texto);
    }
    
    public void setPanelTablero(PanelTablero tableroVisible)
    {
        this.pt= tableroVisible;
    }//fin set

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public JLabel getLblNumeroDeDado() {
        return txtNumeroDeDado;
    }

    public JLabel getLblTurnoDeFicha() {
        return txtTurnoDeFicha;
    }

    public JLabel getTxtTiempo() {
        return txtTiempo;
    }

    public void setTxtTiempo(int valor) {
        txtTiempo.setText( "Tiempo: " + valor );
    }

    public JLabel getTxtPuntosJugador() {
        return txtPuntosJugador;
    }

    public void setTxtPuntosJugador(int valor) {
        txtPuntosJugador.setText("Puntos jugador: " + valor);
    }//

    public JLabel getTxtPuntosOponente() {
        return txtPuntosOponente;
    }

    public void setTxtPuntosOponente(int valor) {
        txtPuntosOponente.setText("Puntos Oponente: " + valor);
    }//

    public JLabel getTxtNumeroDeDado() {
        return txtNumeroDeDado;
    }

    public void setTxtNumeroDeDado(int valor) {
        txtNumeroDeDado.setText("Numero de dado:" + "\n " + valor);
    }//

    public JLabel getTxtTurnoDeFicha() {
        return txtTurnoDeFicha;
    }

    public void setTxtTurnoDeFicha(String valor) {
        txtTurnoDeFicha.setText("Turno de :" + "\n " + valor);
    }//
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtNumeroDeDado = new javax.swing.JLabel();
        txtTurnoDeFicha = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponente = new javax.swing.JLabel();

        btnDado.setText("Dado");
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reinicio");

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        txtNumeroDeDado.setText("Numero de dado");

        txtTurnoDeFicha.setText("Turno de ficha");

        txtTiempo.setText("Tiempo: ");

        txtPuntosJugador.setText("Puntos Jugador:");

        txtPuntosOponente.setText("Puntos Oponente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnDado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnMenu)
                        .addGap(28, 28, 28)
                        .addComponent(btnReinicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtPuntosOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDeDado)
                            .addComponent(txtTurnoDeFicha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTiempo)
                            .addComponent(txtPuntosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtTurnoDeFicha)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroDeDado)
                .addGap(35, 35, 35)
                .addComponent(btnDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnReinicio))
                .addGap(18, 18, 18)
                .addComponent(txtTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPuntosJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPuntosOponente)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:
        /*Coordenadas [] recorrido = tc.getRecorrido();
        for(int i= 0; i<recorrido.length; i++)
        {
           int x = recorrido[i].getX();
           int y = recorrido[i].getY();
           pt.repintar(x, y);
           String eleccion= JOptionPane.showInputDialog("desea continuar?\nDigite ´no´ para parar");
           if(eleccion.equalsIgnoreCase("no"))
           {
               break;
           }
           else
           {
               
               
           }
        }//fin for*/
        
        
        
        
    }//GEN-LAST:event_btnDadoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_btnMenuActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel txtNumeroDeDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponente;
    private javax.swing.JLabel txtTiempo;
    private javax.swing.JLabel txtTurnoDeFicha;
    // End of variables declaration//GEN-END:variables
}
